version: 0.2
phases:
  install:
    commands:
      - echo "Install Phase - Add additional packages if needed."
  pre_build:
    commands:
      - TAG="$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - echo "Update Image tag in kubernetes manifest"
      - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URL:$TAG"'@' manifests/deployment.yaml
      - aws --version
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 186296540553.dkr.ecr.us-west-2.amazonaws.com/nebula-demo-repo
      - export KUBECONFIG=$HOME/.kube/config
  build:
    commands:
      - echo "Docker build started on $(date)"
      - docker build --tag $REPOSITORY_URL:$TAG .
      - echo "Docker build completed on $(date)"
      - docker push $REPOSITORY_URL:$TAG
  post_build:
    commands:
      - echo "Docker image pushed to ECR Repository:$REPOSITORY_URL:$TAG"
      - aws eks update-kubeconfig --name $EKS_CLUSTERNAME
      - aws sts get-caller-identity
      # or kubectl set image deployment/nebula-demo-app nebula-demo-app=$REPOSITORY_URL:$TAG -n nebula-demo
      - kubectl apply -f manifests/
      - echo "Kubernetes deployment updated"
      - printf '[{"name":"deployment.yaml","imageUri":"%s"}]' $REPOSITORY_URL:$TAG > build.json
artifacts:
  files:
    - build.json
    - manifests/*
