apiVersion: apps/v1
kind: Deployment
metadata:
  name: nebula-demo-app
  namespace: nebula-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nebula-demo-app
  template:
    metadata:
      labels:
        app: nebula-demo-app
    spec:
      containers:
        - name: nebula-demo-app
          image: CONTAINER_IMAGE
          ports:
            - containerPort: 80